[project]
name = "tinycudann"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.6.0",
]

[build-system]
requires = [
	"setuptools>=42",
	"torch>=2.6.0"
]
build-backend = "setuptools.build_meta"
